name = "modest"
license = "MIT"
licenselink = "https://github.com/codelamb/modest/blob/master/LICENSE.md"
description = "Minimalistic theme for personal blogs and small NGO's"
homepage = "https://github.com/codelamb/modest/"
tags = ["blog", "plain", "blank", "starter", "CSS Grid", "Cloudinary", "NGO"]
features = ["blog"]
min_version = 0.19

[author]
  name = "codelamb"
  homepage = "https://github.com/codelamb"